[gcp_service_account]
type = "service_account"
project_id = "data-automation-435600"
private_key_id = "b4ebe8f6ddeffc578807e7ea5770f84f8c05549c"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC+YxIH7kPb6g/A
W6qDgW+t7kL7ARHTqWxllQ34icwBzooqq2hk7wyf4Z03CSa7CLTYClUiUxfEJIDD
WtX5JjAGH1+lrMiLzeh7MYtpqyl1du9tuBluhFSq64enTQhXc4mjLwcO9D2E3YFq
DsPDDcmgS59UhzegnkqwvFE3+pK48CL4GwN6v2Q2dGKi/ACyvekV7QxjqX/uKEka
YxR9qb5GBPNxaS6w52W9Ag0gfykjQtfjlNnpomqxcAFF/7Ufwg/sI3j56FL2Zo7x
i6dtvj85K4TVKp5w9jaTAyBWUksCU0XccpQUmR/jK/cfCBFWl/vb+UwFWoq3giHB
bEMXWx05AgMBAAECggEAFxHPpUTelacEzhj9bi5wvylsFdixFY4Fy8BWP0vJO93Q
Wa/H+FUMGVKAF6Nk/Uxmh3gnDT/21QZcUO+wll5letRx5VQsv94NQeJEw6LhJPHq
vMeOU1k3HjfoieH4dQpTvwGLkCkRzEf/7r9HwtqomCMZtScmWzDbGZPUHp2fCkge
6RRno+Ow5eMZCiknYpSXn5C7f51gF0P7taCHXIY4R0Agwm/uU6Db4U6IzMykX1VQ
yzuqop21m7Of7/KUzBHSfA3b+dcrrwqBNNM/I+k2oaOmsIkT1BTu5PGwR6Hil2fW
jMwpTzoLRiB1ouLuF7F5lvQYXY2ks3bMZfu5SnBHpQKBgQD702z2JpUetnKRvNUI
H4q/ubw98VwTqeM3nRx5WCkZH1+/2EhF+ZqQi0GYIKRcuEMFwML+LRXqBt858JWm
NruJ7W69qjmAeojaK1XlqwBU+ONPXJGhyaTacDd0E3RhKcfbfn68mSEAa3BYspjJ
ko4m4Sz5iDQRYb1cE4z4/Is6rQKBgQDBivDW6WcJWhCI0UGviw2AotFkRYu4ysqT
2/aq2BVX67YmUpSS8sE7N+EoYtj2qj3haicjBup7SR1LStstWE2H+TLTILWRJCbg
JW5G7PPYgnBZYHW1TOz1mEWLczFFPFf/1Alz+JnRf2XP8bUQxBOXLyUHBqPDDIbb
n5JAPjzqPQKBgQC396PBSzxjHHwkNaQXdBuDpud7BQj0IIcqiK9Vgm87uCzV1OYv
oIInGGSKA0avqbjkygZpc3xv5CdNh5F7xL5Kq9bb3jB1yI6Te1ccGkl6yfwdbQ3C
+LFjFtmcBd5eYQxtMELb+q4eRV7knUx67YLFqniVrsgC7rlMO8gf2TbJXQKBgEub
fY5XS7sphgAMzz5GchXohShIytZ70juE2I3RMDVSjavW4tetIbOCluDyDJP/2YCv
uW5Di2JyI5GAQrMqJc+SmDpGMufqWY2C0du/QVs5Sa6AsjsLPB6NR828SGkls7Lr
IG4/lcdzn1Bmujc8gfKzpiFihKLzx9MQOVADgER5AoGBALhrtdVPGURkkHSY9P7x
0II+hV+mGvRox+s4dDxkdSL/Bsf69qadAxdpwcwBXSKK1o5HIByWl8SelHwuMz+I
VR5RqXq1Qqwbgtx+X5yAPxWNfVppyHzYRL/LBu/pPNNNJ0eRxteZUs9pEvJuySsf
Eq4jBrcsic2MLmYFNtZ0P4Op
-----END PRIVATE KEY-----"""
client_email = "data-automation@data-automation-435600.iam.gserviceaccount.com"
client_id = "104762573058313077518"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/data-automation%40data-automation-435600.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
